'use strict';
const D=window.FLOATBRIDGE_DATA,E=window.FloatBridge;
const $=id=>document.getElementById(id),money=n=>'৳'+Math.round(n).toLocaleString('en-IN'),pct=n=>(100*n).toFixed(2)+'%';
let state={scenario:D.scenarios[0],agent:D.agents[0].id,approved:false,rejected:false};
const clock=m=>`${String(8+Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
function options(){return {budget:+$('budget').value,visits:+$('visits').value,delay:+$('delay').value,stale:$('stale').checked};}
function reset(){state.approved=false;state.rejected=false;render();}
function metric(label,value,note,highlight=false){return `<div class="metric ${highlight?'highlight':''}"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`;}
function render(){
 const opt=options();state.plan=E.propose(D,state.scenario,'ml',opt);state.base=E.replay(D,state.scenario,state.plan,false);state.result=E.replay(D,state.scenario,state.plan,state.approved);
 $('budget-label').textContent=money(opt.budget);$('scenario-buttons').innerHTML=D.scenarios.map(s=>`<button class="scenario ${s.id===state.scenario.id?'active':''}" data-scenario="${s.id}" aria-pressed="${s.id===state.scenario.id}">${s.title}</button>`).join('');
 document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>{state.scenario=D.scenarios.find(s=>s.id===b.dataset.scenario);reset();});
 $('approval-state').textContent=state.approved?'Approved · replay complete':state.rejected?'Plan rejected':opt.stale?'Paused · stale balances':'Awaiting approval';$('approval-state').className='status-pill'+(state.approved?' approved':'');
 $('outcome-title').textContent=state.approved?'The same demand. A different outcome.':'Review first. Then replay.';
 const b=state.base,r=state.result,delta=b.failed-r.failed;
 $('metrics').innerHTML=metric('FAILED WITHOUT REPLENISHMENT',b.failed,`${b.attempted} attempted requests · ${pct(b.failedRate)}`)+metric(state.approved?'FAILED WITH APPROVED PLAN':'CURRENT FAILED REQUESTS',r.failed,state.approved?`${pct(r.failedRate)} failure rate`:'Approve to apply simulated exchanges',state.approved)+metric('ADDITIONAL REQUESTS COMPLETED',state.approved?(delta>=0?'+':'')+delta:'—',state.approved?'Compared with no replenishment':'Same starting balances & demand')+metric('SIMULATED VISIT COST',money(r.visitCost),`${r.visits} visits × assumed ৳150`);
 $('agent-grid').innerHTML=D.agents.map(a=>{const f=E.forecast(D,a,state.scenario.day);let cum=0,min=0,max=0;f.forEach(p=>{cum+=p.cashIn-p.cashOut;min=Math.min(min,cum);max=Math.max(max,cum);});const risk=a.cash+min<3000||a.efloat-max<3000;return `<button class="agent ${a.id===state.agent?'selected':''}" data-agent="${a.id}" aria-pressed="${a.id===state.agent}"><span class="agent-top">${a.id}<i class="risk-dot ${risk?'high':''}" title="${risk?'Forecast pressure':'Within reserve'}"></i></span><span class="agent-name">${a.name}</span><div class="agent-bar"><i style="width:${100*a.cash/(a.cash+a.efloat)}%"></i></div></button>`;}).join('');
 document.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>{state.agent=b.dataset.agent;render();});
 renderDetail();$('plan-summary').textContent=`${state.plan.items.length} proposed visits · ${money(state.plan.usedBudget||0)} exchange`;$('plan-message').textContent=state.plan.reason;
 $('plan-rows').innerHTML=state.plan.items.length?state.plan.items.map(p=>`<tr><td><strong>${p.name}</strong><small>${p.agent}</small></td><td><span class="receive ${p.delta<0?'efloat':''}">${p.delta>0?'Physical cash':'E-float'}</span></td><td><strong>${money(Math.abs(p.delta))}</strong><small>Matched principal exchange</small></td><td>${clock(p.arrivalMinute)}</td><td>${p.reason}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No exchange proposed. Adjust the constraints or refresh the balance snapshot.</td></tr>';
 $('approve').disabled=state.approved||!state.plan.items.length;$('reject').disabled=state.approved||state.rejected||!state.plan.items.length;
 $('rejected-summary').textContent=`Planning constraints · ${state.plan.rejected.length} candidates not scheduled`;
 $('rejected-items').innerHTML=state.plan.rejected.length?state.plan.rejected.map(p=>`<p>${p.agent} · ${p.name}: ${p.rejection}</p>`).join(''):'<p>All eligible candidates fit the selected constraints.</p>';
 $('activity').innerHTML=r.log.length?r.log.slice(0,12).map(e=>`<div class="audit-row"><span class="audit-time">${clock(e.minute)}</span><strong>${e.agent}</strong><span class="audit-tag ${e.status==='Exchange'?'exchange':''}">${e.status}</span><span>${e.text}</span></div>`).join(''):'<p class="empty">No failed requests or exchanges in this replay.</p>';
}
function renderDetail(){
 const a=D.agents.find(a=>a.id===state.agent),f=E.forecast(D,a,state.scenario.day);$('detail-name').textContent=a.name;$('detail-id').textContent=a.id;
 $('detail-balances').innerHTML=`<div class="balance-cards"><div><span>Opening cash</span><strong>${money(a.cash)}</strong></div><div><span>Opening e-float</span><strong>${money(a.efloat)}</strong></div></div>`;
 const max=Math.max(...f.flatMap(p=>[p.cashIn,p.cashOut]))*1.13,W=370,H=165,top=12,bottom=135;
 let svg=`<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg"><title>Point forecasts of cash-in and cash-out demand in BDT</title>`;
 [0,.5,1].forEach(q=>{let y=bottom-q*(bottom-top);svg+=`<line x1="35" y1="${y}" x2="365" y2="${y}" stroke="#e6ecdf"/><text x="29" y="${y+3}" text-anchor="end" font-size="8" fill="#819079">${Math.round(max*q/1000)}k</text>`;});
 f.forEach((p,i)=>{const x=48+i*53;for(const [v,dx,color]of [[p.cashIn,0,'#39846b'],[p.cashOut,15,'#cc9750']]){const h=(bottom-top)*v/max;svg+=`<rect x="${x+dx}" y="${bottom-h}" width="12" height="${h}" rx="2" fill="${color}"/>`;}svg+=`<text x="${x+13}" y="154" text-anchor="middle" font-size="8" fill="#71806c">${p.hour}:00</text>`;});$('forecast-chart').innerHTML=svg+'</svg>';
 const p=state.plan.items.find(p=>p.agent===a.id);$('detail-reason').textContent=p?`${p.reason} Proposed ${money(Math.abs(p.delta))} matched exchange; arrival ${clock(p.arrivalMinute)}.`:'No exchange selected for this agent under the current constraints. Selection is a heuristic, not a guarantee of availability.';
}
function renderEvidence(){const ev=E.evaluate(D);state.evaluation=ev;
 $('evaluation-metrics').innerHTML='<div class="evidence-cards">'+[['threshold','Static threshold'],['seasonal','Seasonal + same planner'],['ml','Learned forecast + planner']].map(([k,label])=>{const t=ev.totals[k];return `<div class="evidence-card ${k==='ml'?'active':''}"><h3>${label}</h3><div class="big">${t.failed}<small> / ${t.attempted} failed</small></div><p>Failure rate: ${pct(t.failedRate)}</p><p>${t.visits} visits · ${money(t.visits*150)} assumed visit cost</p><p>${money(t.exchange)} total matched exchanges</p></div>`;}).join('')+'</div><p class="footnote">Fixed evaluation settings: ৳60,000 exchange cap and 6 visits per scenario; 60-minute arrival; hub starts with ৳120,000 each in cash and e-float. Operations controls do not change this frozen benchmark. Resource caps are equal; actual costs are not equal.</p>';
 $('evaluation-rows').innerHTML=ev.records.map(r=>`<tr><td>${r.seed}</td><td>${r.ml.attempted}</td><td>${r.threshold.failed}</td><td>${r.seasonal.failed}</td><td><strong>${r.ml.failed}</strong></td></tr>`).join('');
 const m=D.model.metrics;$('forecast-metrics').innerHTML=`<div class="metric-line"><span>Learned forecast WAPE</span><strong>${pct(m.model_wape)}</strong></div><div class="metric-line"><span>Seasonal baseline WAPE</span><strong>${pct(m.seasonal_wape)}</strong></div><div class="metric-line"><span>Untouched test rows</span><strong>${m.test_rows.toLocaleString()}</strong></div><div class="metric-line"><span>Training / validation rows</span><strong>${m.train_rows.toLocaleString()} / ${m.validation_rows.toLocaleString()}</strong></div>`;
}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===b.dataset.page));$('page-title').textContent=({operations:'Keep money moving.',evidence:'Evidence, in the open.',method:'Intelligence you can inspect.'})[b.dataset.page];window.scrollTo(0,0);});
['budget','visits','delay','stale'].forEach(id=>$(id).addEventListener('input',reset));
$('approve').onclick=()=>{state.approved=true;state.rejected=false;render();};$('reject').onclick=()=>{state.rejected=true;state.approved=false;render();};
$('export').onclick=()=>{const data={exportedAt:new Date().toISOString(),notice:'Synthetic demonstration only; no real upay data or financial execution.',version:D.version,scenario:state.scenario.id,seed:state.scenario.seed,options:options(),approved:state.approved,plan:state.plan,baseline:state.base,result:state.result,frozenEvaluation:state.evaluation,model:D.model};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='floatbridge-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
render();renderEvidence();
